### ISSUE TITLE
mail output in BOTS missing

### ISSUE THREAD

**Issue by robcza** [CZ-NIC/intelmq#2]
Missing mail output bot definition in the BOTS file. Has to be defined with all possible parameters and some examples to the actual bot readme file (dev-master branch).

**Comment by e3rd** [comment]
It was only in our private repository.
I put it in installation BOTS file in here, all our three bots, MailGather, MailSend and ForwardDNS Please check it is ok ;)

https://github.com/CZ-NIC/intelmq/blob/dev-master/intelmq/bots/BOTS

**Comment by e3rd** [comment]
https://github.com/CZ-NIC/intelmq/blob/dev-master/intelmq/bots/BOTS
