### ISSUE TITLE
output_send.py parameters

### ISSUE THREAD

**Issue by robcza** [CZ-NIC/intelmq#3]
Configurable parameters would be useful for better testing capabilities:
- "smtp_server": "host/ip"
  - allows to define other smtp server than 127.0.0.1
- "testing_to": "email"
  - overrides all email recipient "To" addresses to a static email (needed for testing purposes)

**Comment by e3rd** [comment]
I've added these two parameters :)
(Both here to dev_master and the configuration to our private repo.)
